apiVersion: apps/v1
kind: Deployment   
metadata:
  name:  testapp   
  namespace: default
  labels:
    app:  testapp
spec:
  selector:
    matchLabels:
      app:  testapp
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  minReadySeconds: 30 
  template:
    metadata:
      labels:
        app:  testapp
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  testapp
        image:  landmarktechth/spring-boot-mongo
        ports:
        - containerPort:  8080
          name:  testapp

      restartPolicy: Always
